apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-watch
  labels:
    app: sw
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sw
  template:
    metadata:
      labels:
        app: sw
    spec:
      containers:
      - name: simple-watch
        image: quay.io/polynomial/simple-watch@sha256:5fbe487ea7d38c262ffc746ccf7b9f420b1b08f4fa5357057aacfeb6a9e32ac8
